### PR TITLE
pyrsia CLI status error

### LINKED ISSUE #239: Pyrsia CLI get status fails
```
pyrsia config --add localhost:7878

pyrsia node -p
Connection Successfull !! {}

pyrsia node -s
Error: error decoding response body: missing field `peers_count` at line 1 column 49
```

### PR DESCRIPTION
**Pull request by MitaliBo**
port change to 7888
somehow status api was overridden by previous changes

Closes #239

### CODE REVIEW

File: pyrsia_node/src/main.rs [hunk 1]
```diff
@@ -55,7 +55,7 @@ use tokio::{
 };
 use warp::Filter;
 
-const DEFAULT_PORT: &str = "7878";
+const DEFAULT_PORT: &str = "7888";
```
Comment (erwin1) [inline pyrsia_node/src/main.rs:58]: if we change the default port, we need to change a number of other things (in fact, I'd prefer a separate issue and PR). Things I think about that needs to change as well:
- the Dockerfile 
- the README
- the message to configure Docker that the linux installers outputs

But there might be other places as well.

Comment (MitaliBo) [reply pyrsia_node/src/main.rs:58]: Agreed created new issue for this #259

**Review by erwin1 — DISMISSED** [review]

**Review by erwin1 — APPROVED** [review]

**Review by fishseabowl — APPROVED** [review]
If possible, please add unit tests. thanks
