### PR TITLE
Repeatedly adding the same node

### LINKED ISSUE #1581: Repeatedly adding the same node
### Steps taken/Steps to reproduce

Adding the same node_id repeatedly is still ok.
Reproducer can be found [here](https://github.com/pyrsia/pyrsia/pull/1538#discussion_r1094935808).

### Expected Behavior

 By design, if an authority node is already in the Pyrsia network and has not been removed, we will not add it again to prevent committing useless blocks.

### Experienced Instance of the bug

rustc 1.66.1 (90743e729 2023-01-10)
Mac OS
v0.2.3

### PR DESCRIPTION
**Pull request by dgarus**
## Description

Fixes #1581 

- added node checks for `TransparencyLogService::remove_authorized_node` method
- made `TransparencyLogService::write_transparency_log` method private
- extended `TransparencyLogService::add_artifact` to insert a log record to the database
- added according tests

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've run [pre-commit.sh](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.sh) ([pre-commit.bat](https://github.com/pyrsia/pyrsia/blob/main/pre-commit.bat)) successfully.
- [x] I've run the [integrations tests](https://github.com/pyrsia/pyrsia-integration-tests#how-to-set-up-and-run-the-tests)
on the PR branch and all tests passes.

### CODE REVIEW

File: src/artifact_service/service.rs [hunk 1]
```diff
@@ -217,13 +215,9 @@ impl ArtifactService {
...
-            if let Err(TransparencyLogError::LogNotFound { .. }) = self
-                .transparency_log_service
-                .find_transparency_log(&transparency_log.id)
-            {
-                self.transparency_log_service
-                    .write_transparency_log(&transparency_log)?;
-            }
+            self.transparency_log_service
+                .write_if_not_exists(&transparency_log)
+                .await?;
```
Comment (fishseabowl) [inline src/artifact_service/service.rs:220]: It looks good to me. But maybe this wrapper is unnecessary.

File: src/transparency_log/log.rs [hunk 2]
```diff
@@ -226,9 +239,24 @@ impl TransparencyLogService {
             .add_block(payload.into_bytes())
             .await?;
 
+        self.write_transparency_log(&transparency_log)?;
+
```
Comment (fishseabowl) [inline src/transparency_log/log.rs:243]: Could you explain the advantages of this modification in detail? Thanks

Comment (dgarus) [reply src/transparency_log/log.rs:243]: 1. After every calling `add_artifact` follows `write_transparency_log`. So, the first reason is decreasing code duplication because we don't have reason to repeat this code block in different places.
2. If we want to control what we write to the database, we should encapsulate `write_transparency_log` otherwise we have no context for checks. Hence, we should use this method only inside TransparencyLogService's high-level methods like 'add_artifact', 'remove_authorized_node' and so on.

File: src/artifact_service/service.rs (hunk 1 above)
Comment (dgarus) [reply src/artifact_service/service.rs:220]: The main aim is encapsulation `write_transparency_log`.

**Review by fishseabowl — APPROVED** [review]
lgtm

**Review by dasmanas — APPROVED** [review]
